
services:
  redis:
    image: redis:7.4-alpine
    restart: unless-stopped
    env_file:
      - .env.docker
    command: ["sh", "-c", "redis-server --appendonly yes --requirepass \"$$REDIS_PASSWORD\""]    
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$$REDIS_PASSWORD\" ping"]
      interval: 10s
      timeout: 3s
      retries: 10
  app:
    build: .
    restart: always
    env_file:
      - .env.docker
    environment:
      - CHOKIDAR_USEPOLLING=1
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  redis_data: